### PR TITLE
Use better pattern to match for sofe parent name

### PR DESCRIPTION
**Pull request by lbntly**

### CODE REVIEW

**Comment by joeldenning** [comment]
Nice work on this. :+1: . @lbntly I was thinking about this some more and maybe we should make sure that the `sofe@0.0.0.js` is after a `!`, since anything after the `!` indicates the name of the systemjs plugin that is being used.

@blittle thoughts on this? @lbntly and I found a bug caused by this because the `parentName` was a url that coincidentally had `sofe` in it, even though the parent was not a sofe service.

**Comment by joeldenning** [comment]
Also, looks like the tests are failing possibly because the tests use the local version of the sofe plugin which doesn't have a `@1.0.0` in it. see https://github.com/CanopyTax/sofe/blob/32f5fce15807022e503b299ede0dfee9c5cd64d2/test/localStorage.test.js#L27 for what I mean. We might have to change the regex or maybe find a way to get the tests to pass without changing the regex.

**Comment by blittle** [comment]
Looks good! Let's merge after the tests are fixed and push a new version.

**Comment by lbntly** [comment]
@joeldenning I changed the pattern to accept `@x.x.x` optionally. Do you think it's still good enough? I'm not too worried about the `!` because it could be `!` followed by an entire URL path, and I'm not sure we need to worry about false positives too much.

**Comment by joeldenning** [comment]
@lbntly that sounds good to me. Let's merge and publish.

**Comment by blittle** [comment]
Published as `v1.1.5`

**Pull request merged**
